//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("CuisineModel", "FK_T_Commentaire_T_Recette", "T_Recette", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WebApplication.T_Recette), "T_Commentaire", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebApplication.T_Commentaire), true)]
[assembly: EdmRelationshipAttribute("CuisineModel", "FK_T_Commentaire_T_User", "T_User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WebApplication.T_User), "T_Commentaire", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebApplication.T_Commentaire), true)]
[assembly: EdmRelationshipAttribute("CuisineModel", "FK_T_Conseil_T_User", "T_User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WebApplication.T_User), "T_Conseil", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebApplication.T_Conseil), true)]
[assembly: EdmRelationshipAttribute("CuisineModel", "FK_T_UserRecette_T_Recette", "T_Recette", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WebApplication.T_Recette), "T_Favoris", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebApplication.T_Favoris), true)]
[assembly: EdmRelationshipAttribute("CuisineModel", "FK_T_UserRecette_T_User", "T_User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WebApplication.T_User), "T_Favoris", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebApplication.T_Favoris), true)]
[assembly: EdmRelationshipAttribute("CuisineModel", "FK_T_RecetteIngredient_T_Ingredient", "T_Ingredient", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WebApplication.T_Ingredient), "T_RecetteIngredient", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebApplication.T_RecetteIngredient), true)]
[assembly: EdmRelationshipAttribute("CuisineModel", "FK_T_Note_T_Recette", "T_Recette", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(WebApplication.T_Recette), "T_Note", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebApplication.T_Note), true)]
[assembly: EdmRelationshipAttribute("CuisineModel", "FK_T_Note_T_User", "T_User", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(WebApplication.T_User), "T_Note", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebApplication.T_Note), true)]
[assembly: EdmRelationshipAttribute("CuisineModel", "FK_T_Recette_T_User", "T_User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WebApplication.T_User), "T_Recette", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebApplication.T_Recette), true)]
[assembly: EdmRelationshipAttribute("CuisineModel", "FK_T_RecetteIngredient_T_Recette", "T_Recette", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WebApplication.T_Recette), "T_RecetteIngredient", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebApplication.T_RecetteIngredient), true)]

#endregion

namespace WebApplication
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CuisineEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CuisineEntities object using the connection string found in the 'CuisineEntities' section of the application configuration file.
        /// </summary>
        public CuisineEntities() : base("name=CuisineEntities", "CuisineEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CuisineEntities object.
        /// </summary>
        public CuisineEntities(string connectionString) : base(connectionString, "CuisineEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CuisineEntities object.
        /// </summary>
        public CuisineEntities(EntityConnection connection) : base(connection, "CuisineEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<T_Commentaire> T_Commentaire
        {
            get
            {
                if ((_T_Commentaire == null))
                {
                    _T_Commentaire = base.CreateObjectSet<T_Commentaire>("T_Commentaire");
                }
                return _T_Commentaire;
            }
        }
        private ObjectSet<T_Commentaire> _T_Commentaire;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<T_Conseil> T_Conseil
        {
            get
            {
                if ((_T_Conseil == null))
                {
                    _T_Conseil = base.CreateObjectSet<T_Conseil>("T_Conseil");
                }
                return _T_Conseil;
            }
        }
        private ObjectSet<T_Conseil> _T_Conseil;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<T_Favoris> T_Favoris
        {
            get
            {
                if ((_T_Favoris == null))
                {
                    _T_Favoris = base.CreateObjectSet<T_Favoris>("T_Favoris");
                }
                return _T_Favoris;
            }
        }
        private ObjectSet<T_Favoris> _T_Favoris;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<T_Ingredient> T_Ingredient
        {
            get
            {
                if ((_T_Ingredient == null))
                {
                    _T_Ingredient = base.CreateObjectSet<T_Ingredient>("T_Ingredient");
                }
                return _T_Ingredient;
            }
        }
        private ObjectSet<T_Ingredient> _T_Ingredient;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<T_Note> T_Note
        {
            get
            {
                if ((_T_Note == null))
                {
                    _T_Note = base.CreateObjectSet<T_Note>("T_Note");
                }
                return _T_Note;
            }
        }
        private ObjectSet<T_Note> _T_Note;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<T_Recette> T_Recette
        {
            get
            {
                if ((_T_Recette == null))
                {
                    _T_Recette = base.CreateObjectSet<T_Recette>("T_Recette");
                }
                return _T_Recette;
            }
        }
        private ObjectSet<T_Recette> _T_Recette;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<T_RecetteIngredient> T_RecetteIngredient
        {
            get
            {
                if ((_T_RecetteIngredient == null))
                {
                    _T_RecetteIngredient = base.CreateObjectSet<T_RecetteIngredient>("T_RecetteIngredient");
                }
                return _T_RecetteIngredient;
            }
        }
        private ObjectSet<T_RecetteIngredient> _T_RecetteIngredient;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<T_User> T_User
        {
            get
            {
                if ((_T_User == null))
                {
                    _T_User = base.CreateObjectSet<T_User>("T_User");
                }
                return _T_User;
            }
        }
        private ObjectSet<T_User> _T_User;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the T_Commentaire EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToT_Commentaire(T_Commentaire t_Commentaire)
        {
            base.AddObject("T_Commentaire", t_Commentaire);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the T_Conseil EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToT_Conseil(T_Conseil t_Conseil)
        {
            base.AddObject("T_Conseil", t_Conseil);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the T_Favoris EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToT_Favoris(T_Favoris t_Favoris)
        {
            base.AddObject("T_Favoris", t_Favoris);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the T_Ingredient EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToT_Ingredient(T_Ingredient t_Ingredient)
        {
            base.AddObject("T_Ingredient", t_Ingredient);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the T_Note EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToT_Note(T_Note t_Note)
        {
            base.AddObject("T_Note", t_Note);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the T_Recette EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToT_Recette(T_Recette t_Recette)
        {
            base.AddObject("T_Recette", t_Recette);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the T_RecetteIngredient EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToT_RecetteIngredient(T_RecetteIngredient t_RecetteIngredient)
        {
            base.AddObject("T_RecetteIngredient", t_RecetteIngredient);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the T_User EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToT_User(T_User t_User)
        {
            base.AddObject("T_User", t_User);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CuisineModel", Name="T_Commentaire")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_Commentaire : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new T_Commentaire object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="utilisateurID">Initial value of the utilisateurID property.</param>
        /// <param name="recetteID">Initial value of the recetteID property.</param>
        public static T_Commentaire CreateT_Commentaire(global::System.Int64 id, global::System.Int64 utilisateurID, global::System.Int64 recetteID)
        {
            T_Commentaire t_Commentaire = new T_Commentaire();
            t_Commentaire.id = id;
            t_Commentaire.utilisateurID = utilisateurID;
            t_Commentaire.recetteID = recetteID;
            return t_Commentaire;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String texte
        {
            get
            {
                return _texte;
            }
            set
            {
                OntexteChanging(value);
                ReportPropertyChanging("texte");
                _texte = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("texte");
                OntexteChanged();
            }
        }
        private global::System.String _texte;
        partial void OntexteChanging(global::System.String value);
        partial void OntexteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 utilisateurID
        {
            get
            {
                return _utilisateurID;
            }
            set
            {
                OnutilisateurIDChanging(value);
                ReportPropertyChanging("utilisateurID");
                _utilisateurID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("utilisateurID");
                OnutilisateurIDChanged();
            }
        }
        private global::System.Int64 _utilisateurID;
        partial void OnutilisateurIDChanging(global::System.Int64 value);
        partial void OnutilisateurIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 recetteID
        {
            get
            {
                return _recetteID;
            }
            set
            {
                OnrecetteIDChanging(value);
                ReportPropertyChanging("recetteID");
                _recetteID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("recetteID");
                OnrecetteIDChanged();
            }
        }
        private global::System.Int64 _recetteID;
        partial void OnrecetteIDChanging(global::System.Int64 value);
        partial void OnrecetteIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CuisineModel", "FK_T_Commentaire_T_Recette", "T_Recette")]
        public T_Recette T_Recette
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Recette>("CuisineModel.FK_T_Commentaire_T_Recette", "T_Recette").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Recette>("CuisineModel.FK_T_Commentaire_T_Recette", "T_Recette").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<T_Recette> T_RecetteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Recette>("CuisineModel.FK_T_Commentaire_T_Recette", "T_Recette");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<T_Recette>("CuisineModel.FK_T_Commentaire_T_Recette", "T_Recette", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CuisineModel", "FK_T_Commentaire_T_User", "T_User")]
        public T_User T_User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_User>("CuisineModel.FK_T_Commentaire_T_User", "T_User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_User>("CuisineModel.FK_T_Commentaire_T_User", "T_User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<T_User> T_UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_User>("CuisineModel.FK_T_Commentaire_T_User", "T_User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<T_User>("CuisineModel.FK_T_Commentaire_T_User", "T_User", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CuisineModel", Name="T_Conseil")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_Conseil : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new T_Conseil object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="idCreateur">Initial value of the idCreateur property.</param>
        /// <param name="texte">Initial value of the texte property.</param>
        /// <param name="nom">Initial value of the nom property.</param>
        public static T_Conseil CreateT_Conseil(global::System.Int64 id, global::System.Int64 idCreateur, global::System.String texte, global::System.String nom)
        {
            T_Conseil t_Conseil = new T_Conseil();
            t_Conseil.id = id;
            t_Conseil.idCreateur = idCreateur;
            t_Conseil.texte = texte;
            t_Conseil.nom = nom;
            return t_Conseil;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 idCreateur
        {
            get
            {
                return _idCreateur;
            }
            set
            {
                OnidCreateurChanging(value);
                ReportPropertyChanging("idCreateur");
                _idCreateur = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idCreateur");
                OnidCreateurChanged();
            }
        }
        private global::System.Int64 _idCreateur;
        partial void OnidCreateurChanging(global::System.Int64 value);
        partial void OnidCreateurChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String texte
        {
            get
            {
                return _texte;
            }
            set
            {
                OntexteChanging(value);
                ReportPropertyChanging("texte");
                _texte = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("texte");
                OntexteChanged();
            }
        }
        private global::System.String _texte;
        partial void OntexteChanging(global::System.String value);
        partial void OntexteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String photo
        {
            get
            {
                return _photo;
            }
            set
            {
                OnphotoChanging(value);
                ReportPropertyChanging("photo");
                _photo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("photo");
                OnphotoChanged();
            }
        }
        private global::System.String _photo;
        partial void OnphotoChanging(global::System.String value);
        partial void OnphotoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nom
        {
            get
            {
                return _nom;
            }
            set
            {
                OnnomChanging(value);
                ReportPropertyChanging("nom");
                _nom = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nom");
                OnnomChanged();
            }
        }
        private global::System.String _nom;
        partial void OnnomChanging(global::System.String value);
        partial void OnnomChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> dateCreation
        {
            get
            {
                return _dateCreation;
            }
            set
            {
                OndateCreationChanging(value);
                ReportPropertyChanging("dateCreation");
                _dateCreation = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dateCreation");
                OndateCreationChanged();
            }
        }
        private Nullable<global::System.DateTime> _dateCreation;
        partial void OndateCreationChanging(Nullable<global::System.DateTime> value);
        partial void OndateCreationChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CuisineModel", "FK_T_Conseil_T_User", "T_User")]
        public T_User T_User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_User>("CuisineModel.FK_T_Conseil_T_User", "T_User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_User>("CuisineModel.FK_T_Conseil_T_User", "T_User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<T_User> T_UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_User>("CuisineModel.FK_T_Conseil_T_User", "T_User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<T_User>("CuisineModel.FK_T_Conseil_T_User", "T_User", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CuisineModel", Name="T_Favoris")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_Favoris : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new T_Favoris object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="userID">Initial value of the userID property.</param>
        /// <param name="recetteID">Initial value of the recetteID property.</param>
        public static T_Favoris CreateT_Favoris(global::System.Int64 id, global::System.Int64 userID, global::System.Int64 recetteID)
        {
            T_Favoris t_Favoris = new T_Favoris();
            t_Favoris.id = id;
            t_Favoris.userID = userID;
            t_Favoris.recetteID = recetteID;
            return t_Favoris;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 userID
        {
            get
            {
                return _userID;
            }
            set
            {
                OnuserIDChanging(value);
                ReportPropertyChanging("userID");
                _userID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("userID");
                OnuserIDChanged();
            }
        }
        private global::System.Int64 _userID;
        partial void OnuserIDChanging(global::System.Int64 value);
        partial void OnuserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 recetteID
        {
            get
            {
                return _recetteID;
            }
            set
            {
                OnrecetteIDChanging(value);
                ReportPropertyChanging("recetteID");
                _recetteID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("recetteID");
                OnrecetteIDChanged();
            }
        }
        private global::System.Int64 _recetteID;
        partial void OnrecetteIDChanging(global::System.Int64 value);
        partial void OnrecetteIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CuisineModel", "FK_T_UserRecette_T_Recette", "T_Recette")]
        public T_Recette T_Recette
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Recette>("CuisineModel.FK_T_UserRecette_T_Recette", "T_Recette").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Recette>("CuisineModel.FK_T_UserRecette_T_Recette", "T_Recette").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<T_Recette> T_RecetteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Recette>("CuisineModel.FK_T_UserRecette_T_Recette", "T_Recette");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<T_Recette>("CuisineModel.FK_T_UserRecette_T_Recette", "T_Recette", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CuisineModel", "FK_T_UserRecette_T_User", "T_User")]
        public T_User T_User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_User>("CuisineModel.FK_T_UserRecette_T_User", "T_User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_User>("CuisineModel.FK_T_UserRecette_T_User", "T_User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<T_User> T_UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_User>("CuisineModel.FK_T_UserRecette_T_User", "T_User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<T_User>("CuisineModel.FK_T_UserRecette_T_User", "T_User", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CuisineModel", Name="T_Ingredient")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_Ingredient : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new T_Ingredient object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="nom">Initial value of the nom property.</param>
        public static T_Ingredient CreateT_Ingredient(global::System.Int64 id, global::System.String nom)
        {
            T_Ingredient t_Ingredient = new T_Ingredient();
            t_Ingredient.id = id;
            t_Ingredient.nom = nom;
            return t_Ingredient;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nom
        {
            get
            {
                return _nom;
            }
            set
            {
                OnnomChanging(value);
                ReportPropertyChanging("nom");
                _nom = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nom");
                OnnomChanged();
            }
        }
        private global::System.String _nom;
        partial void OnnomChanging(global::System.String value);
        partial void OnnomChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CuisineModel", "FK_T_RecetteIngredient_T_Ingredient", "T_RecetteIngredient")]
        public EntityCollection<T_RecetteIngredient> T_RecetteIngredient
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_RecetteIngredient>("CuisineModel.FK_T_RecetteIngredient_T_Ingredient", "T_RecetteIngredient");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_RecetteIngredient>("CuisineModel.FK_T_RecetteIngredient_T_Ingredient", "T_RecetteIngredient", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CuisineModel", Name="T_Note")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_Note : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new T_Note object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static T_Note CreateT_Note(global::System.Int64 id)
        {
            T_Note t_Note = new T_Note();
            t_Note.id = id;
            return t_Note;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> idUser
        {
            get
            {
                return _idUser;
            }
            set
            {
                OnidUserChanging(value);
                ReportPropertyChanging("idUser");
                _idUser = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idUser");
                OnidUserChanged();
            }
        }
        private Nullable<global::System.Int64> _idUser;
        partial void OnidUserChanging(Nullable<global::System.Int64> value);
        partial void OnidUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> idRecette
        {
            get
            {
                return _idRecette;
            }
            set
            {
                OnidRecetteChanging(value);
                ReportPropertyChanging("idRecette");
                _idRecette = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idRecette");
                OnidRecetteChanged();
            }
        }
        private Nullable<global::System.Int64> _idRecette;
        partial void OnidRecetteChanging(Nullable<global::System.Int64> value);
        partial void OnidRecetteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> note
        {
            get
            {
                return _note;
            }
            set
            {
                OnnoteChanging(value);
                ReportPropertyChanging("note");
                _note = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("note");
                OnnoteChanged();
            }
        }
        private Nullable<global::System.Int32> _note;
        partial void OnnoteChanging(Nullable<global::System.Int32> value);
        partial void OnnoteChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CuisineModel", "FK_T_Note_T_Recette", "T_Recette")]
        public T_Recette T_Recette
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Recette>("CuisineModel.FK_T_Note_T_Recette", "T_Recette").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Recette>("CuisineModel.FK_T_Note_T_Recette", "T_Recette").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<T_Recette> T_RecetteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Recette>("CuisineModel.FK_T_Note_T_Recette", "T_Recette");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<T_Recette>("CuisineModel.FK_T_Note_T_Recette", "T_Recette", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CuisineModel", "FK_T_Note_T_User", "T_User")]
        public T_User T_User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_User>("CuisineModel.FK_T_Note_T_User", "T_User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_User>("CuisineModel.FK_T_Note_T_User", "T_User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<T_User> T_UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_User>("CuisineModel.FK_T_Note_T_User", "T_User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<T_User>("CuisineModel.FK_T_Note_T_User", "T_User", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CuisineModel", Name="T_Recette")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_Recette : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new T_Recette object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="nom">Initial value of the nom property.</param>
        /// <param name="introduction">Initial value of the introduction property.</param>
        /// <param name="realisation">Initial value of the realisation property.</param>
        /// <param name="createurID">Initial value of the createurID property.</param>
        /// <param name="temps_prepa">Initial value of the temps_prepa property.</param>
        public static T_Recette CreateT_Recette(global::System.Int64 id, global::System.String nom, global::System.String introduction, global::System.String realisation, global::System.Int64 createurID, global::System.Int32 temps_prepa)
        {
            T_Recette t_Recette = new T_Recette();
            t_Recette.id = id;
            t_Recette.nom = nom;
            t_Recette.introduction = introduction;
            t_Recette.realisation = realisation;
            t_Recette.createurID = createurID;
            t_Recette.temps_prepa = temps_prepa;
            return t_Recette;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nom
        {
            get
            {
                return _nom;
            }
            set
            {
                OnnomChanging(value);
                ReportPropertyChanging("nom");
                _nom = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nom");
                OnnomChanged();
            }
        }
        private global::System.String _nom;
        partial void OnnomChanging(global::System.String value);
        partial void OnnomChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String introduction
        {
            get
            {
                return _introduction;
            }
            set
            {
                OnintroductionChanging(value);
                ReportPropertyChanging("introduction");
                _introduction = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("introduction");
                OnintroductionChanged();
            }
        }
        private global::System.String _introduction;
        partial void OnintroductionChanging(global::System.String value);
        partial void OnintroductionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String realisation
        {
            get
            {
                return _realisation;
            }
            set
            {
                OnrealisationChanging(value);
                ReportPropertyChanging("realisation");
                _realisation = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("realisation");
                OnrealisationChanged();
            }
        }
        private global::System.String _realisation;
        partial void OnrealisationChanging(global::System.String value);
        partial void OnrealisationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String difficulte
        {
            get
            {
                return _difficulte;
            }
            set
            {
                OndifficulteChanging(value);
                ReportPropertyChanging("difficulte");
                _difficulte = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("difficulte");
                OndifficulteChanged();
            }
        }
        private global::System.String _difficulte;
        partial void OndifficulteChanging(global::System.String value);
        partial void OndifficulteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String photo
        {
            get
            {
                return _photo;
            }
            set
            {
                OnphotoChanging(value);
                ReportPropertyChanging("photo");
                _photo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("photo");
                OnphotoChanged();
            }
        }
        private global::System.String _photo;
        partial void OnphotoChanging(global::System.String value);
        partial void OnphotoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 createurID
        {
            get
            {
                return _createurID;
            }
            set
            {
                OncreateurIDChanging(value);
                ReportPropertyChanging("createurID");
                _createurID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("createurID");
                OncreateurIDChanged();
            }
        }
        private global::System.Int64 _createurID;
        partial void OncreateurIDChanging(global::System.Int64 value);
        partial void OncreateurIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> temps_cuisson
        {
            get
            {
                return _temps_cuisson;
            }
            set
            {
                Ontemps_cuissonChanging(value);
                ReportPropertyChanging("temps_cuisson");
                _temps_cuisson = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("temps_cuisson");
                Ontemps_cuissonChanged();
            }
        }
        private Nullable<global::System.Int32> _temps_cuisson;
        partial void Ontemps_cuissonChanging(Nullable<global::System.Int32> value);
        partial void Ontemps_cuissonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> temps_repos
        {
            get
            {
                return _temps_repos;
            }
            set
            {
                Ontemps_reposChanging(value);
                ReportPropertyChanging("temps_repos");
                _temps_repos = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("temps_repos");
                Ontemps_reposChanged();
            }
        }
        private Nullable<global::System.Int32> _temps_repos;
        partial void Ontemps_reposChanging(Nullable<global::System.Int32> value);
        partial void Ontemps_reposChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 temps_prepa
        {
            get
            {
                return _temps_prepa;
            }
            set
            {
                Ontemps_prepaChanging(value);
                ReportPropertyChanging("temps_prepa");
                _temps_prepa = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("temps_prepa");
                Ontemps_prepaChanged();
            }
        }
        private global::System.Int32 _temps_prepa;
        partial void Ontemps_prepaChanging(global::System.Int32 value);
        partial void Ontemps_prepaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> date
        {
            get
            {
                return _date;
            }
            set
            {
                OndateChanging(value);
                ReportPropertyChanging("date");
                _date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date");
                OndateChanged();
            }
        }
        private Nullable<global::System.DateTime> _date;
        partial void OndateChanging(Nullable<global::System.DateTime> value);
        partial void OndateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String categorie
        {
            get
            {
                return _categorie;
            }
            set
            {
                OncategorieChanging(value);
                ReportPropertyChanging("categorie");
                _categorie = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("categorie");
                OncategorieChanged();
            }
        }
        private global::System.String _categorie;
        partial void OncategorieChanging(global::System.String value);
        partial void OncategorieChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CuisineModel", "FK_T_Commentaire_T_Recette", "T_Commentaire")]
        public EntityCollection<T_Commentaire> T_Commentaire
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_Commentaire>("CuisineModel.FK_T_Commentaire_T_Recette", "T_Commentaire");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_Commentaire>("CuisineModel.FK_T_Commentaire_T_Recette", "T_Commentaire", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CuisineModel", "FK_T_UserRecette_T_Recette", "T_Favoris")]
        public EntityCollection<T_Favoris> T_Favoris
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_Favoris>("CuisineModel.FK_T_UserRecette_T_Recette", "T_Favoris");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_Favoris>("CuisineModel.FK_T_UserRecette_T_Recette", "T_Favoris", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CuisineModel", "FK_T_Note_T_Recette", "T_Note")]
        public EntityCollection<T_Note> T_Note
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_Note>("CuisineModel.FK_T_Note_T_Recette", "T_Note");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_Note>("CuisineModel.FK_T_Note_T_Recette", "T_Note", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CuisineModel", "FK_T_Recette_T_User", "T_User")]
        public T_User T_User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_User>("CuisineModel.FK_T_Recette_T_User", "T_User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_User>("CuisineModel.FK_T_Recette_T_User", "T_User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<T_User> T_UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_User>("CuisineModel.FK_T_Recette_T_User", "T_User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<T_User>("CuisineModel.FK_T_Recette_T_User", "T_User", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CuisineModel", "FK_T_RecetteIngredient_T_Recette", "T_RecetteIngredient")]
        public EntityCollection<T_RecetteIngredient> T_RecetteIngredient
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_RecetteIngredient>("CuisineModel.FK_T_RecetteIngredient_T_Recette", "T_RecetteIngredient");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_RecetteIngredient>("CuisineModel.FK_T_RecetteIngredient_T_Recette", "T_RecetteIngredient", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CuisineModel", Name="T_RecetteIngredient")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_RecetteIngredient : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new T_RecetteIngredient object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="recetteID">Initial value of the recetteID property.</param>
        /// <param name="ingredientID">Initial value of the ingredientID property.</param>
        public static T_RecetteIngredient CreateT_RecetteIngredient(global::System.Int64 id, global::System.Int64 recetteID, global::System.Int64 ingredientID)
        {
            T_RecetteIngredient t_RecetteIngredient = new T_RecetteIngredient();
            t_RecetteIngredient.id = id;
            t_RecetteIngredient.recetteID = recetteID;
            t_RecetteIngredient.ingredientID = ingredientID;
            return t_RecetteIngredient;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 recetteID
        {
            get
            {
                return _recetteID;
            }
            set
            {
                OnrecetteIDChanging(value);
                ReportPropertyChanging("recetteID");
                _recetteID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("recetteID");
                OnrecetteIDChanged();
            }
        }
        private global::System.Int64 _recetteID;
        partial void OnrecetteIDChanging(global::System.Int64 value);
        partial void OnrecetteIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ingredientID
        {
            get
            {
                return _ingredientID;
            }
            set
            {
                OningredientIDChanging(value);
                ReportPropertyChanging("ingredientID");
                _ingredientID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ingredientID");
                OningredientIDChanged();
            }
        }
        private global::System.Int64 _ingredientID;
        partial void OningredientIDChanging(global::System.Int64 value);
        partial void OningredientIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CuisineModel", "FK_T_RecetteIngredient_T_Ingredient", "T_Ingredient")]
        public T_Ingredient T_Ingredient
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Ingredient>("CuisineModel.FK_T_RecetteIngredient_T_Ingredient", "T_Ingredient").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Ingredient>("CuisineModel.FK_T_RecetteIngredient_T_Ingredient", "T_Ingredient").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<T_Ingredient> T_IngredientReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Ingredient>("CuisineModel.FK_T_RecetteIngredient_T_Ingredient", "T_Ingredient");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<T_Ingredient>("CuisineModel.FK_T_RecetteIngredient_T_Ingredient", "T_Ingredient", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CuisineModel", "FK_T_RecetteIngredient_T_Recette", "T_Recette")]
        public T_Recette T_Recette
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Recette>("CuisineModel.FK_T_RecetteIngredient_T_Recette", "T_Recette").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Recette>("CuisineModel.FK_T_RecetteIngredient_T_Recette", "T_Recette").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<T_Recette> T_RecetteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Recette>("CuisineModel.FK_T_RecetteIngredient_T_Recette", "T_Recette");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<T_Recette>("CuisineModel.FK_T_RecetteIngredient_T_Recette", "T_Recette", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CuisineModel", Name="T_User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new T_User object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="password">Initial value of the password property.</param>
        /// <param name="nom">Initial value of the nom property.</param>
        public static T_User CreateT_User(global::System.Int64 id, global::System.String password, global::System.String nom)
        {
            T_User t_User = new T_User();
            t_User.id = id;
            t_User.password = password;
            t_User.nom = nom;
            return t_User;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nom
        {
            get
            {
                return _nom;
            }
            set
            {
                OnnomChanging(value);
                ReportPropertyChanging("nom");
                _nom = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nom");
                OnnomChanged();
            }
        }
        private global::System.String _nom;
        partial void OnnomChanging(global::System.String value);
        partial void OnnomChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String info
        {
            get
            {
                return _info;
            }
            set
            {
                OninfoChanging(value);
                ReportPropertyChanging("info");
                _info = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("info");
                OninfoChanged();
            }
        }
        private global::System.String _info;
        partial void OninfoChanging(global::System.String value);
        partial void OninfoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CuisineModel", "FK_T_Commentaire_T_User", "T_Commentaire")]
        public EntityCollection<T_Commentaire> T_Commentaire
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_Commentaire>("CuisineModel.FK_T_Commentaire_T_User", "T_Commentaire");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_Commentaire>("CuisineModel.FK_T_Commentaire_T_User", "T_Commentaire", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CuisineModel", "FK_T_Conseil_T_User", "T_Conseil")]
        public EntityCollection<T_Conseil> T_Conseil
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_Conseil>("CuisineModel.FK_T_Conseil_T_User", "T_Conseil");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_Conseil>("CuisineModel.FK_T_Conseil_T_User", "T_Conseil", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CuisineModel", "FK_T_UserRecette_T_User", "T_Favoris")]
        public EntityCollection<T_Favoris> T_Favoris
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_Favoris>("CuisineModel.FK_T_UserRecette_T_User", "T_Favoris");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_Favoris>("CuisineModel.FK_T_UserRecette_T_User", "T_Favoris", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CuisineModel", "FK_T_Note_T_User", "T_Note")]
        public EntityCollection<T_Note> T_Note
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_Note>("CuisineModel.FK_T_Note_T_User", "T_Note");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_Note>("CuisineModel.FK_T_Note_T_User", "T_Note", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CuisineModel", "FK_T_Recette_T_User", "T_Recette")]
        public EntityCollection<T_Recette> T_Recette
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_Recette>("CuisineModel.FK_T_Recette_T_User", "T_Recette");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_Recette>("CuisineModel.FK_T_Recette_T_User", "T_Recette", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
